<center><img src="https://drive.google.com/uc?export=view&id=1f0tvL6DLzfOQ_xHNdaBe_6fDUd27lc6U" alt="PSUT"  width="180px"> 
<p> 
King Hussein School for Computing Sciences <br>
Department of Data Science <br>
Data Engineering Lab <br>
Python Review, Jupyter Notebook, & Google Colab 
</p></center>

  [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github.com/alhaol/psut-de/blob/main/reviews/Lecture_1_PythonReview.ipynb)

<h1> Install Anaconda </h1>
<h4> System requirements </h4>
<ul>
<li>License: Free use and redistribution under the terms of the End User License Agreement - Anaconda® Individual Edition. </li>
<li>Operating system: Windows 8 or newer, 64-bit macOS 10.13+, or Linux, including Ubuntu, RedHat, CentOS 6+, and others.</li>
<li>If your operating system is older than what is currently supported, you can find older versions of the Anaconda installers in our archive that might work for you. See Using Anaconda on older operating systems for version recommendations.</li>
<li>System architecture: Windows- 64-bit x86, 32-bit x86; MacOS- 64-bit x86; Linux- 64-bit x86, 64-bit Power8/Power9.</li>
<li>Minimum 5 GB disk space to download and install.</li>
</ul>

<h4> Installation Instructions:</h4>
<ul>
<li><a href = "https://docs.anaconda.com/anaconda/install/windows/"> Installing on Windows</a> </li>
<li><a href = "https://docs.anaconda.com/anaconda/install/mac-os/"> Installing on macOS</a></li>
<li><a href = "https://docs.anaconda.com/anaconda/install/linux/"> Installing on Linux</a></li>
</ul>

<h1> Loading and saving data from external sources - Google Colab </h1>
<h4> Uploading files from your local file system</h4>

``````
from google.colab import files
uploaded = files.upload()
``````

<h4> Downloading files to your local file system</h4>

``````
from google.colab import files
with open('example.txt', 'w') as f:
  f.write('some content')
files.download('example.txt')
``````

<h4> Google Drive</h4>
You can access files in Drive in a number of ways, including:
<ul>
<li> Mounting your Google Drive in the runtime's virtual machine <br>
The example below shows how to mount your Google Drive on your runtime using an authorization code, and how to write and read files there. Once executed, you will be able to see the new file (foo.txt) at https://drive.google.com/.

This only supports reading, writing, and moving files; to programmatically modify sharing settings or other metadata, use one of the other options below.

Note: When using the 'Mount Drive' button in the file browser, no authentication codes are necessary for notebooks that have only been edited by the current user.

`````
from google.colab import drive
drive.mount('/content/drive')
with open('/content/drive/My Drive/foo.txt', 'w') as f:
  f.write('Hello Google Drive!')
!cat /content/drive/My\ Drive/foo.txt
drive.flush_and_unmount()
print('All changes made in this colab session should now be visible in Drive.')
`````

</li>
<li> Using the <a here="https://developers.google.com/drive/api/v3/about-sdk">native REST API</a></li>
</ul>

<h5> For More Information check this <a href="https://colab.research.google.com/notebooks/io.ipynb#scrollTo=D78AM1fFt2ty" > Ref </a></h5>


<h1> Why Python?!</h1>
<ol>
<li> <b>Easy to Learn and Use.</b> It has simplified syntax and not complicated, which gives more emphasis on natural language.  </li>
<li> <b>Mature and Supportive Python Community.</b>  There are plenty of documentation, guides and Video Tutorials for Python language are available that learner and developer of any skill level or ages can use and receive the support required to enhance their knowledge in python programming language.  </li>
<li> <b>Support from Renowned Corporate Sponsors.</b> Python Programming language is heavily backed by Facebook, Amazon Web Services, and especially Google.  </li>
<li> <b>Hundreds of Python Libraries and Frameworks.</b> Python has excellent libraries that you can use to select and save your time and effort on the initial cycle of development. </li>
<li> <b>Versatility, Efficiency, Reliability, and Speed.</b> Python can be used in nearly any kind of environment, and one will not face any kind of performance loss issue irrespective of the platform one is working. </li>
<li> <b>Big data, Machine Learning and Cloud Computing.</b> Cloud Computing, Machine Learning, and Big Data are some of the hottest trends in the computer science world right now. Python language is one of the most popular used tool for data science and analytics.  </li>
<li> <b>The Flexibility of Python Language.</b> The python language is so flexible that it gives the developer the chance to try something new. The person who is an expert in python language is not just limited to build similar kinds of things but can also go on to try to make something different than before. </li>

</ol>


<h1> Python Basic operations </h1>

**The answer is so and so**

<h2> Simple Python math <h2> 
  <p> Python supports all of the math operations that you would expect. The basic ones are addition, subtraction, multiplication, and division. Other ones include the exponentiation and modulo operators.</p>

In [ ]:
# Addition, add two int together
1+1

In [ ]:
# if one of the operands is a float, the result is a float.
5.0*6

In [ ]:
5*6

In [ ]:
# integer division
200/5

In [ ]:
# Exponentiation ** 
# This operator raises the number to its left to the power of the number to its right 
2**3

In [ ]:
# Modulo
# Returns the remainder of the division of the number to the left by the 
# number on its right. 
9%3

In [ ]:
# Define variable
x = 2 
y = 3
# output statment 
print("x= ", x)
print("y= ", y)
x+y

<h2> Using pre-defined math functions </h2>
<p> <b>math package</b> provides access to the mathematical functions defined by the C standard.</p>
<p>For more detials, check this <a href="https://docs.python.org/3/library/math.html" >Ref</a></p>

In [ ]:
import math


In [ ]:
# importing math
from math import *
x=1;y=2
# Using some math functions
print(sin(x))
print(sqrt(y+6))
print(cos(x))

0.8414709848078965
2.8284271247461903
0.5403023058681398


<h2> Numpy Array Basics </h2>
<p> <b>NumPy package</b> (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. NumPy gives you an enormous range of fast and efficient ways of creating arrays and manipulating numerical data inside them.  </p>

<h4> Why use NumPy?</h4>
NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further.

<h4> What is an array?</h4>
An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype.

<img src = "https://numpy.org/devdocs/_images/np_array.png">

<h4> How to create a basic array?</h4>
Different functions can be used to define an array:  np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), and np.linspace().
<ul>
<li> np.array()-> to create an array using a list.</li>
<li>np.zeros()-> to create an array filled with 0’s. </li>
<li>np.ones()-> to create an array filled with 1’s. </li>
<li> np.empty()-> to create an array whose initial content is random and depends on the state of the memory.</li> 
<li>np.arange()-> to create an array with a range of elements. </li>
<li>np.linspace()-> to create an array with values that are spaced linearly in a specified interval. </li>
</ul>

Using Numpy you are able to create nD-arrays. Such array is called also a Matrix. For example, this is an 2D-array 

`````
data = np.array([[1, 2], [3, 4]])
`````

<img src = "https://numpy.org/devdocs/_images/np_create_matrix.png">

<p> For more details, check this <a href="https://numpy.org/devdocs/user/absolute_beginners.html">Ref</a></p>

In [ ]:
# Defining 2D array of ones
my2DArrayO = np.ones((3))
print("2D array of ones\n",my2DArrayO)

2D array of ones
 [1. 1. 1.]


In [ ]:
# importing numpy
import numpy as np

# Defining 1D array
my1DArray = np.array([1, 8, 27, 64])
print("1D array\n",my1DArray)

# Defining 1D array of zeros
my1DArrayZ = np.zeros(5)
print("1D array of zeors\n",my1DArrayZ)

# Defining 2D array of ones
my2DArrayO = np.ones((3))
print("2D array of ones\n",my2DArrayO)

# Empty array
emptyArray = np.empty((3,2))
print("Empty array \n",emptyArray)

# Array of evenly-spaced values
### evenly-spaced value can be made given a starting point, a stopping point, and a number of elements.
evenSpacedArray = np.linspace(0, 1, 6)
print("Array of evenly-spaced 6 values between 0 and 1 \n",evenSpacedArray)

# Array of evenly-spaced values
### evenly-spaced value can be made given a starting point, a stopping point, and a step.
evenSpacedArray = np.arange(10,25,5)
print("Array of evenly-spaced values between [10-25] and a step = 5 \n",evenSpacedArray)




1D array
 [ 1  8 27 64]
1D array of zeors
 [0. 0. 0. 0. 0.]
2D array of ones
 [1. 1. 1.]
Empty array 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
Array of evenly-spaced 6 values between 0 and 1 
 [0.  0.2 0.4 0.6 0.8 1. ]
Array of evenly-spaced values between [10-25] and a step = 5 
 [10 15 20]


In [ ]:
# Defining and printing 2D array
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])
print("2D array\n",my2DArray)

# Defining 2D array of ones
my2DArrayO = np.ones((3,3))
print("2D array of ones\n",my2DArrayO)

#Defining and printing 3D array
my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]])
print("3D array\n",my3Darray)

# Array with random values
randArr = np.random.random((2,2))
print("Random Array \n", randArr)

2D array
 [[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]
2D array of ones
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3D array
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]
Random Array 
 [[0.90958314 0.91417577]
 [0.0246375  0.3997506 ]]


In [ ]:
# Print out memory address
print(my2DArray.data)

# Print the shape of array
print(my2DArray.shape)

# Print out the data type of the array
print(my2DArray.dtype)

# Print the number of `my2DArray`'s dimensions
print(my2DArray.ndim)

# Print the number of `my2DArray`'s elements
print(my2DArray.size)

(3, 4)
int64
2
12


<h3> Broadcasting in NumPy </h3>
<p>There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. </p>

`````
data = np.array([1.0, 2.0])
data * 1.6
array([1.6, 3.2])
`````
<img src = "https://numpy.org/devdocs/_images/np_multiply_broadcasting.png">


`````
a = array([[ 0.0,  0.0,  0.0],
            [10.0, 10.0, 10.0],
            [20.0, 20.0, 20.0],
            [30.0, 30.0, 30.0]])
b = array([1.0, 2.0, 3.0])
a + b
`````

<img src = "https://numpy.org/devdocs/_images/theory.broadcast_2.gif">

When the <u>trailing dimensions of the arrays are unequal</u>, broadcasting <b>FAILS</b> because it is impossible to align the values in the rows of the 1st array with the elements of the 2nd arrays for element-by-element addition.

<img src = "https://numpy.org/devdocs/_images/theory.broadcast_3.gif">

<b>Broadcasting</b> is a mechanism that allows NumPy to perform operations on arrays of different shapes. <br>

<b>Broadcasting two arrays together follow these rules:</b> <br>
Rule 1: Two dimensions are operatable if they are equal <br>
Rule 2: Two dimensions are also comptable when one of them is 1 <br>
Rule 3: Arrays can be broadcasted together if they are compatible in all dimensions <br>


For more details, check this <a href="https://numpy.org/devdocs/user/theory.broadcasting.html" >Ref</a>

In [ ]:
# Create an array of two dimension
import numpy as np
A =np.ones((2,3))
B = np.random.random((2,3))

In [ ]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y.reshape((2,5)).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# Create an array of two dimension
import numpy as np
A =np.ones((2,3))
B = np.random.random((2,3))

# Shape of A
print("A Shape" , A.shape)
print("B Shape" ,B.shape)

print("A \n",A)
print("B \n",B)

# Sum of A and B, here the shape of both the matrix is same.
print("A+B \n", A + B)

In [ ]:
# Initialize `x`
x = np.ones((3,4))
print("x \n",x)

# Check shape of `x`
print("x shape \n",x.shape)

# Initialize `y`
y = np.arange(4)
print("y \n",y)

# Check shape of `y`
print("y shape \n",y.shape)

# Subtract `x` and `y`
x - y 

x 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
x shape 
 (3, 4)
y 
 [0 1 2 3]
y shape 
 (4,)


array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

<h3>Numpy and mathematics</h3>

In [ ]:
# Basica operations (+, -, *, /, %)
x = np.array([[1, 2, 3], [2, 3, 4]])
y = np.array([[1, 4, 9], [2, 3, -2]])

# Add two array
add = np.add(x, y)
print("x+y \n",add)

# Subtract two array
sub = np.subtract(x, y)
print("x-y \n",sub)

# Multipley two array
mul = np.multiply(x, y)
print("x*y \n",mul)

# Divide x, y
div = np.divide(x,y)
print("x/y \n",div)

# Calculated the remainder of x and y
rem = np.remainder(x, y)
print("x%y \n",rem)

x+y 
 [[ 2  6 12]
 [ 4  6  2]]
x-y 
 [[ 0 -2 -6]
 [ 0  0  6]]
x*y 
 [[ 1  8 27]
 [ 4  9 -8]]
x/y 
 [[ 1.          0.5         0.33333333]
 [ 1.          1.         -2.        ]]
x%y 
 [[0 2 3]
 [0 0 0]]


<h2> Python Dictionaries</h2>
<p> <b>Dictionary</b> is a composite data type that is a collection of objects.</p>

<h4> Defining a Dictionary</h4>
<p>A dictionary consists of a collection of key-value pairs. Each key-value pair maps the key to its associated value. Dictionary elements are accessed via keys.</p>

`````
dict = {
    <key1>: <value1>,
    <key2>: <value2>,
      .
      .
      .
    <keyN>: <valueN>
}

dict[<key1>]
`````

`````
D = {'name': 'Bob',
     'age': 25,
     'job': 'Dev',
     'city': 'New York',
     'email': 'bob@web.com'}
`````

<img src = "https://www.learnbyexample.org/wp-content/uploads/python/Dictionary-Key-Value-Pairs-Illustration.png">


For more details, check this <a href="https://docs.python.org/3/tutorial/datastructures.html#dictionaries">Ref</a>

In [ ]:
#Declare dictionay 
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [ ]:
#Declare dictionay 
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

#Accessing Items
print(thisdict["model"])
print(thisdict.get("brand"))

#Change Values
print("Previous year: ",thisdict["year"])
thisdict["year"] = 2018
print("Current year: ",thisdict["year"])

#Dictionary Length
print("Number of elements in dict:",len(thisdict))

#Adding Items
thisdict["color"] = "red"
print(thisdict)

#Copy a Dictionary
mydict = thisdict.copy()
print(mydict)

#Removing Items
thisdict.pop("model")
print(thisdict)

del thisdict["year"]
print(thisdict)

#Removing the Last Inserted Item
thisdict.popitem()
print(thisdict)

#Empty Dictionary
thisdict.clear()
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}
Mustang
Ford
Previous year:  1964
Current year:  2018
Number of elements in dict: 3
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018, 'color': 'red'}
{'brand': 'Ford', 'model': 'Mustang', 'year': 2018, 'color': 'red'}
{'brand': 'Ford', 'year': 2018, 'color': 'red'}
{'brand': 'Ford', 'color': 'red'}
{'brand': 'Ford'}
{}


<h2>Data strcutre of pandas</h2>

<ul><li>Series-> a one-dimensional ndarray with axis labels (including time series) that is capable of holding data of any type

`````
pandas.Series( data, index, dtype, copy)
`````
For more details, check <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html" > Ref 1</a> and <a href="https://www.tutorialspoint.com/python_pandas/python_pandas_series.htm" > Ref 2</a>
</li>
<li>DataFrames-> a two-dimensional, size-mutable, potentially heterogeneous tabular data. </li>

<img src ="https://media.geeksforgeeks.org/wp-content/uploads/finallpandas.png" width="500px">

For example:

`````
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
df = pd.DataFrame(data)
print(df)
`````

<img src ="https://media.geeksforgeeks.org/wp-content/uploads/df2-1.png" >

For more details, check <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html" > Ref 1</a> and <a href="https://www.geeksforgeeks.org/python-pandas-dataframe/" > Ref 2</a>
</ul>

In [ ]:
# Importing pandas
import pandas as pd

#Declear Series
series = pd.Series([2, 3, 7, 11, 13])
print("Series: \n", series, "\n")


Series: 
 0     2
1     3
2     7
3    11
4    13
dtype: int64 



In [ ]:
series.to_list()[-1]

13

In [ ]:
# Creating dataframe from Dictionary
dict = [{'A': 'Apple', 'B': 'Ball'},{'A': 'Aeroplane', 'B': 'Bat', 'C': 'Cat'}]
dict_df = pd.DataFrame(dict)
print("Dict: \n",dict,"\n")
print("A DF from Dict\n",dict_df,"\n")

Dict: 
 [{'A': 'Apple', 'B': 'Ball'}, {'A': 'Aeroplane', 'B': 'Bat', 'C': 'Cat'}] 

A DF from Dict
            A     B    C
0      Apple  Ball  NaN
1  Aeroplane   Bat  Cat 



In [ ]:
dict_df

A     B    C
0      Apple  Ball  NaN
1  Aeroplane   Bat  Cat

In [ ]:
# Creating dataframe from Dictionary
dict = [{'A': 'Apple', 'B': 'Ball'},{'A': 'Aeroplane', 'B': 'Bat', 'C': 'Cat'}]
dict_df = pd.DataFrame(dict)
print("Dict: \n",dict,"\n")
print("A DF from Dict\n",dict_df,"\n")
  
# Creating dataframe from Series
series_df = pd.DataFrame({
    'A': range(1, 5),
    'B': pd.Timestamp('20190526'),
    'C': pd.Series(5, index=list(range(4)), dtype='float64'),
    'D': np.array([3]*4, dtype='int64'),
    'E': pd.Categorical(["Depression", "Social Anxiety", "Bipolar Disorder", "Eating Disorder"]),
    'F': 'Mental health',
    'G': 'is challenging'
})
print("A DF from Series\n",series_df,"\n")

# Creating a dataframe from ndarrays
sdf = {
    'County':['Østfold', 'Hordaland', 'Oslo', 'Hedmark', 'Oppland', 'Buskerud'],
    'ISO-Code':[1,2,3,4,5,6],
    'Area': [4180.69, 4917.94, 454.07, 27397.76, 25192.10, 14910.94],
    'Administrative centre': ["Sarpsborg", "Oslo", "City of Oslo", "Hamar", "Lillehammer", "Drammen"]
    }
sdf = pd.DataFrame(sdf)
print("A DF from ndarrays\n",sdf,"\n")


#Dataframe Shape
print("Shape: ",sdf.shape)