<center><img src="https://drive.google.com/uc?export=view&id=1f0tvL6DLzfOQ_xHNdaBe_6fDUd27lc6U" alt="PSUT"  width="180px"> 
<p> 
King Hussein School for Computing Sciences <br>
Department of Data Science <br>
Data Engineering Lab <br>
Python Review, Jupyter Notebook, & Google Colab 
</p></center>

  [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github.com/alhaol/psut-de/blob/main/reviews/Lecture_2_PythonReview.ipynb)

<h1> Install Anaconda </h1>
<h4> System requirements </h4>
<ul>
<li>License: Free use and redistribution under the terms of the End User License Agreement - Anaconda® Individual Edition. </li>
<li>Operating system: Windows 8 or newer, 64-bit macOS 10.13+, or Linux, including Ubuntu, RedHat, CentOS 6+, and others.</li>
<li>If your operating system is older than what is currently supported, you can find older versions of the Anaconda installers in our archive that might work for you. See Using Anaconda on older operating systems for version recommendations.</li>
<li>System architecture: Windows- 64-bit x86, 32-bit x86; MacOS- 64-bit x86; Linux- 64-bit x86, 64-bit Power8/Power9.</li>
<li>Minimum 5 GB disk space to download and install.</li>
</ul>

<h4> Installation Instructions:</h4>
<ul>
<li><a href = "https://docs.anaconda.com/anaconda/install/windows/"> Installing on Windows</a> </li>
<li><a href = "https://docs.anaconda.com/anaconda/install/mac-os/"> Installing on macOS</a></li>
<li><a href = "https://docs.anaconda.com/anaconda/install/linux/"> Installing on Linux</a></li>
</ul>

<h1> Loading and saving data from external sources - Google Colab </h1>
<h4> Uploading files from your local file system</h4>

``````
from google.colab import files
uploaded = files.upload()
``````

<h4> Downloading files to your local file system</h4>

``````
from google.colab import files
with open('example.txt', 'w') as f:
  f.write('some content')
files.download('example.txt')
``````

<h4> Google Drive</h4>
You can access files in Drive in a number of ways, including:
<ul>
<li> Mounting your Google Drive in the runtime's virtual machine <br>
The example below shows how to mount your Google Drive on your runtime using an authorization code, and how to write and read files there. Once executed, you will be able to see the new file (foo.txt) at https://drive.google.com/.

This only supports reading, writing, and moving files; to programmatically modify sharing settings or other metadata, use one of the other options below.

Note: When using the 'Mount Drive' button in the file browser, no authentication codes are necessary for notebooks that have only been edited by the current user.

`````
from google.colab import drive
drive.mount('/content/drive')
with open('/content/drive/My Drive/foo.txt', 'w') as f:
  f.write('Hello Google Drive!')
!cat /content/drive/My\ Drive/foo.txt
drive.flush_and_unmount()
print('All changes made in this colab session should now be visible in Drive.')
`````

</li>
<li> Using the <a here="https://developers.google.com/drive/api/v3/about-sdk">native REST API</a></li>
</ul>

<h5> For More Information check this <a href="https://colab.research.google.com/notebooks/io.ipynb#scrollTo=D78AM1fFt2ty" > Ref </a></h5>


<h1> Why Python?!</h1>
<ol>
<li> <b>Easy to Learn and Use.</b> It has simplified syntax and not complicated, which gives more emphasis on natural language.  </li>
<li> <b>Mature and Supportive Python Community.</b>  There are plenty of documentation, guides and Video Tutorials for Python language are available that learner and developer of any skill level or ages can use and receive the support required to enhance their knowledge in python programming language.  </li>
<li> <b>Support from Renowned Corporate Sponsors.</b> Python Programming language is heavily backed by Facebook, Amazon Web Services, and especially Google.  </li>
<li> <b>Hundreds of Python Libraries and Frameworks.</b> Python has excellent libraries that you can use to select and save your time and effort on the initial cycle of development. </li>
<li> <b>Versatility, Efficiency, Reliability, and Speed.</b> Python can be used in nearly any kind of environment, and one will not face any kind of performance loss issue irrespective of the platform one is working. </li>
<li> <b>Big data, Machine Learning and Cloud Computing.</b> Cloud Computing, Machine Learning, and Big Data are some of the hottest trends in the computer science world right now. Python language is one of the most popular used tool for data science and analytics.  </li>
<li> <b>The Flexibility of Python Language.</b> The python language is so flexible that it gives the developer the chance to try something new. The person who is an expert in python language is not just limited to build similar kinds of things but can also go on to try to make something different than before. </li>

</ol>


<h1> Python Review:</h1>
<h3> Numpy, Dictionary, Series, DataFrame, Function, loop and control statements</h3>

<h2>More & More about array, dataframe </h2>

Often when faced with a large amount of data, a first step is to compute summary statistics for the data in question. Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the "typical" values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).

`NumPy` has fast <u>built-in</u> aggregation functions for working on arrays: `np.sum`, `np.min`, `np.max`, `np.mean`, `np.median`, `np.std`, and `np.prod`. Also, `NumPy` has fast sorting functions: `np.sort` and `np.argsort`.

`Pandas` also has fast <u>built-in</u> summarization functions for working on dataframes: `info`, `shape`, and `describe`. Using the built-in function (`columns`), you can retrieve the columns of a dataframe. 

In [2]:
import numpy as np

L = np.random.random(10)
print(L,'\n')

# Summing the Values in an Array
print(sum(L))
print(np.sum(L),'\n')

# Minimum and Maximum
print("Min= ", min(L))
print("Max= ",np.max(L),'\n')

# Product of elements
print("Prod= ", np.prod(L))



[0.49818196 0.54285199 0.70933449 0.3575627  0.7387699  0.51835678
 0.72990943 0.50795992 0.66164571 0.78932399] 

6.053896887784442
6.053896887784443 

Min=  0.35756270446917315
Max=  0.7893239933666768 

Prod=  0.005086158967527479


In [3]:
M = np.random.random((3, 4))
print(M,"\n")

# Summing the Values in a 2D-Array
print(M.sum(),"\n")

# The Min value within each column
print("Min value/col: ", M.min(axis=0))

# The Max value within each row
print("Max value/row: ", M.max(axis=1))


[[0.61962731 0.5862941  0.89922395 0.10260399]
 [0.56660224 0.53498745 0.14889557 0.7258822 ]
 [0.49334065 0.18794544 0.05265037 0.02354366]] 

4.941596920585633 

Min value/col:  [0.49334065 0.18794544 0.05265037 0.02354366]
Max value/row:  [0.89922395 0.7258822  0.49334065]


In [4]:
# Revision of Broadcasting
a = np.array([0, 1, 2])

print("a ", a,"\n" )

print("a*2 ", a*2, '\n')
print("---------------------------------")
###############################
b = np.array([5, 5, 5])

print("b ", b, '\n')

print("a * b ", np.multiply(a,b), '\n')
print("---------------------------------")
###############################
c=  np.ones((3, 3))

print ("c ",c, '\n')

print("a+c", np.add(a,c), '\n')
print("---------------------------------")
###############################
d = np.random.random((3,4))

print ("d ",d, '\n')

print("b*d", np.multiply(b,d), '\n')

a  [0 1 2] 

a*2  [0 2 4] 

---------------------------------
b  [5 5 5] 

a * b  [ 0  5 10] 

---------------------------------
c  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

a+c [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]] 

---------------------------------
d  [[0.21634235 0.1347284  0.57886083 0.44477752]
 [0.96740687 0.24404157 0.34757184 0.19750306]
 [0.3995332  0.4792001  0.66524948 0.88690322]] 



ValueError: ignored

In [5]:
x = np.array([2, 1, 4, 3, 5])
print("x ",x,'\n') 

# Sorting the elements of an array 
print("Sorted ",np.sort(x),'\n') 

# Indices of the sorted elements
print("Indx of Sorted Ele",np.argsort(x),'\n')

x  [2 1 4 3 5] 

Sorted  [1 2 3 4 5] 

Indx of Sorted Ele [1 0 3 2 4] 



In [8]:
y = np.random.randint(0, 10, (4, 6))
print("y ",y,'\n') 
# sort each column of y
print("Sorted cols \n",np.sort(y, axis=0),'\n') 
# sort each row of y
print("Sorted rows \n",np.sort(y, axis=1),'\n') 

y  [[2 8 5 6 4 4]
 [8 7 5 3 9 7]
 [4 1 4 9 8 9]
 [8 2 1 4 6 9]] 

Sorted cols 
 [[2 1 1 3 4 4]
 [4 2 4 4 6 7]
 [8 7 5 6 8 9]
 [8 8 5 9 9 9]] 

Sorted rows 
 [[2 4 4 5 6 8]
 [3 5 7 7 8 9]
 [1 4 4 8 9 9]
 [1 2 4 6 8 9]] 



In [9]:
import pandas as pd
sdf = {
    'County':['Østfold', 'Hordaland', 'Oslo', 'Hedmark', 'Oppland', 'Buskerud'],
    'ISO-Code':[1,2,3,4,5,6],
    'Area': [4180.69, 4917.94, 454.07, 27397.76, 25192.10, 14910.94],
    'Administrative centre': ["Sarpsborg", "Oslo", "City of Oslo", "Hamar", "Lillehammer", "Drammen"]
    }

df = pd.DataFrame(sdf)
print("DF \n",df,"\n")

# Displays the rows, columns, data types and memory used by the dataframe
print("Display df info \n")
df.info()


# Displays the no of data points and columns in the dataframe
print("\nDF shape \n",df.shape,'\n')

# Display all columns of the dataframe
print("DF columns \n",df.columns,'\n')

# Displays summary statistics for each numerical column in the dataframe
print("Display df summary \n")
df.describe()

DF 
       County  ISO-Code      Area Administrative centre
0    Østfold         1   4180.69             Sarpsborg
1  Hordaland         2   4917.94                  Oslo
2       Oslo         3    454.07          City of Oslo
3    Hedmark         4  27397.76                 Hamar
4    Oppland         5  25192.10           Lillehammer
5   Buskerud         6  14910.94               Drammen 

Display df info 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   County                 6 non-null      object 
 1   ISO-Code               6 non-null      int64  
 2   Area                   6 non-null      float64
 3   Administrative centre  6 non-null      object 
dtypes: float64(1), int64(1), object(2)
memory usage: 320.0+ bytes

DF shape 
 (6, 4) 

DF columns 
 Index(['County', 'ISO-Code', 'Area', 'Administrative centre'], dtype='object'

ISO-Code          Area
count  6.000000      6.000000
mean   3.500000  12842.250000
std    1.870829  11488.650565
min    1.000000    454.070000
25%    2.250000   4365.002500
50%    3.500000   9914.440000
75%    4.750000  22621.810000
max    6.000000  27397.760000

<h2> Functions </h2>
<p>A function is a block of organized, reusable code that is used to perform a single, related action. Functions provide better modularity for your application and a high degree of code reusing.</p>

<h4> Defining a Function</h4>
You can define functions to provide the required functionality. Rules to define a function in Python:
<ul>
<li>Function blocks begin with the keyword def followed by the function name and parentheses ( ( ) ). </li>

<li>Any input parameters or arguments should be placed within these parentheses. You can also define parameters inside these parentheses. </li>

<li>The first statement of a function can be an optional statement - the documentation string of the function or docstring.</li>

<li>The code block within every function starts with a colon (:) and is indented.</li>

<li>The statement return [expression] exits a function, optionally passing back an expression to the caller. A return statement with no arguments is the same as return None.</li>
</ul>

`````
def functionname( parameters ):
   "function_docstring"
   function_suite
   return [expression]
`````


In [10]:
# Defining a function
def printme():
    print ("Print from printme function\n\n")

# Calling a function  
printme()


###########################
# Defining a function
def Fun2(str):
    print ("Your Str is \n", str)

# Calling a function  
Fun2("I'm first call to user defined function!")
Fun2("Again second call to the same function")


Print from printme function


Your Str is 
 I'm first call to user defined function!
Your Str is 
 Again second call to the same function


In [11]:
def printArray(arr):
  for i in range (0,len(arr)):
    if (i % 2) == 0:
      print("An Even Index = ",i," stores ", arr[i])
    else:
      print("An Odd Index = ",i," stores ", arr[i])

###########################################
x = np.array([2, 1, 4, 3, 5])
printArray(x)


An Even Index =  0  stores  2
An Odd Index =  1  stores  1
An Even Index =  2  stores  4
An Odd Index =  3  stores  3
An Even Index =  4  stores  5


In [13]:
def printArray(arr):
  for i in range (0,len(arr)):
    if (i % 2) == 0:
      print("An Even Index = ",i," stores ", arr[i])
    else:
      print("An Odd Index = ",i," stores ", arr[i])
  Sum = sum(arr)
  Mean = Sum/len(arr)
  return Sum, Mean

###########################################
S,M = printArray(x)
x,y,z = 3,4,5
print(x,y,z)

if (S > 50):
  print( S , " > 50")
elif S >2 and S <10:
  print("2 < ", S, " < 10")
else:
  print ("\nSum = ", S)

print("Mean = ", M)



An Even Index =  0  stores  2
An Odd Index =  1  stores  1
An Even Index =  2  stores  4
An Odd Index =  3  stores  3
An Even Index =  4  stores  5
3 4 5

Sum =  15
Mean =  3.0
